version: "3"

services:
  captura:
    build: .
    command: ng serve --host 0.0.0.0
    ports:
    - 4200:4200
    networks:
      - microservices

networks:
  microservices:
    external:
      name: network_microservices